### ISSUE TITLE
Are there any plans to update / support the Carnival Unity Plugin?

### ISSUE THREAD

**Issue by SarahRiordan** [carnivalmobile/carnival-sdk-unity#5]
As noted in title, customer has reached out in past, and recently to request an update to the Carnival-Unity plugin. 

Sam has spoken to the customer already and has estimated a 1 day estimate for the scope. 

No further information is needed from the client for this request.

**Comment by codybunea** [comment]
This issue was moved to carnivalmobile/features#583
